import pygame
from pygame.locals import *

from core.event import *
from core.constants import *
from core.controller import *

class KeyboardController(Controller):
	"""KeyboardController takes Pygame events generated by the
	keyboard and uses them to control the model, by sending Requests
	or to control the Pygame display directly, as with the QuitEvent
	"""
	def __init__(self):
		Controller.__init__(self)

	def defaultAction(self):
		for pygameEvent in pygame.event.get():
			event = None
			if pygameEvent.type == QUIT:
				event = QuitEvent()

			elif pygameEvent.type == KEYDOWN and pygameEvent.key == K_ESCAPE:
				event = QuitEvent()

			elif pygameEvent.type == KEYDOWN and pygameEvent.key == K_UP:
				event = ChangeSpeedEvent(DELAY_DOWN)

			elif pygameEvent.type == KEYDOWN and pygameEvent.key == K_DOWN:
				event = ChangeSpeedEvent(DELAY_UP)

			elif pygameEvent.type == KEYDOWN and pygameEvent.key == K_LEFT:
				event = ChangeSpeedEvent(DELAY_UP)

			elif pygameEvent.type == KEYDOWN and pygameEvent.key == K_RIGHT:
				event = ChangeSpeedEvent(DELAY_DOWN)

			if event:
				self.trigger(event)

