#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License version 3 as
published by the Free Software Foundation.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program. If not, see <http://www.gnu.org/licenses/>.
"""
__author__ = "Rubens Pinheiro Gonçalves Cavalcante"
__date__ = "08/05/13 19:18"
__licence__ = "GPLv3"
__email__ = "rubenspgcavalcante@gmail.com"

class Event(object):
    """this is a superclass for any events that might be generated by an
    object and sent to the EventManager"""

    def __init__(self):
        self.name = "Generic Event"


class TickEvent(Event):
    def __init__(self):
        Event.__init__(self)
        self.name = "CPU Tick Event"


class QuitEvent(Event):
    def __init__(self):
        Event.__init__(self)
        self.name = "Program Quit Event"


class GameStartEvent(Event):
    def __init__(self):
        Event.__init__(self)
        self.name = "Game Started Event"


class AppStartEvent(Event):
    def __init__(self):
        Event.__init__(self)
        self.name = "App Started Event"


class AppStartEvent(Event):
    def __init__(self):
        Event.__init__(self)
        self.name = "App Started Event"


class KeyboardEvent(Event):
    def __init__(self, key=None):
        Event.__init__(self)
        self.name = "Keyboard Event"
        self.key = key


class MouseEvent(Event):
    def __init__(self, button=None):
        Event.__init__(self)
        self.name = "Mouse Event"
        self.button = button


class SetCellEvent(Event):
    def __init__(self, posx=None, posy=None):
        Event.__init__(self)
        self.name = "Set Cell Event"
        self.posx = posx
        self.posy = posy


class CellAddedEvent(Event):
    def __init__(self, posx=None, posy=None):
        Event.__init__(self)
        self.name = "Cell Added Event"
        self.posx = posx
        self.posy = posy


class DelCellEvent(Event):
    def __init__(self, posx=None, posy=None):
        Event.__init__(self)
        self.name = "Delete Cell Event"
        self.posx = posx
        self.posy = posy


class CellRemovedEvent(Event):
    def __init__(self, posx=None, posy=None):
        Event.__init__(self)
        self.name = "Cell Removed Event"
        self.posx = posx
        self.posy = posy


class PauseEvent(Event):
    def __init__(self):
        Event.__init__(self)
        self.name = "Pause Event"

class SaveEvent(Event):
    def __init__(self):
        Event.__init__(self)
        self.name = "Save event"

class LoadEvent(Event):
    def __init__(self):
        Event.__init__(self)
        self.name = "Load event"

class LoadErrorEvent(Event):
    def __init__(self):
        Event.__init__(self)
        self.name = "Load error event"

class ChangeSpeedEvent(Event):
    UP = 1
    DOWN = 0

    def __init__(self, delayChange=None):
        Event.__init__(self)
        self.name = "Change Speed Event"
        self.delayChange = delayChange
        if delayChange < 0:
            self.state = ChangeSpeedEvent.UP
        else:
            self.state = ChangeSpeedEvent.DOWN


class ScreenAvaibleEvent(Event):
    def __init__(self, screen=None):
        Event.__init__(self)
        self.name = "Screen Avaible Event"
        self.screen = screen


class ShowNotificationEvent(Event):
    def __init__(self, notification=None, error=False):
        Event.__init__(self)
        self.name = "Show notification"
        self.error = error
        self.notification = notification

class DisplayRefreshEvent(Event):
    def __init__(self, layer=None):
        Event.__init__(self)
        self.name = "Display Refresh"
        self.layer = layer