class Event:
    """this is a superclass for any events that might be generated by an
    object and sent to the EventManager"""
    def __init__(self):
        self.name = "Generic Event"

class TickEvent(Event):
	def __init__(self):
		self.name = "CPU Tick Event"

class QuitEvent(Event):
	def __init__(self):
		self.name = "Program Quit Event"

class GameStartEvent(Event):
	def __init__(self):
		self.name = "Game Started Event"

class AppStartEvent(Event):
	def __init__(self):
		self.name = "App Started Event"

class AppStartEvent(Event):
    def __init__(self):
        self.name = "App Started Event"

class NewGenerationEvent(Event):
    def __init__(self, whitelist=None, blacklist=None):
        self.name = "New Generation Event"
        self.whitelist = whitelist
        self.blacklist = blacklist

class ChangeSpeedEvent(Event):
    def __init__(self, delayChange=None):
        self.name = "Change Speed Event"
        self.delayChange = delayChange